### PR TITLE
Improve <style> processing

### PR DESCRIPTION
**Pull request by boris-ulyanov**

### CODE REVIEW

**Comment by darealshinji** [comment]
Thanks for your contribution. I will check this later. Maybe you should do a PR to the upstream repository too: https://github.com/memononen/nanosvg/pulls

**Comment by darealshinji** [comment]
I'm getting an error:
```
nanosvg.h:2861:35: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]

   char* rv = strstr(s, "<![CDATA[");
```

**Comment by darealshinji** [comment]
Okay the issue is that in C++ `strstr()` is provided as 2 overloaded functions:
``` C++
const char * strstr ( const char * str1, const char * str2 );
      char * strstr (       char * str1, const char * str2 );
```
So in this case it expects `str1` to be a `const char *`.

I made this quick workaround, but there's probably a better solution:
``` diff
@@ -2839,6 +2835,11 @@ static char *nsvg__strndup(const char *s, size_t n)
 	return (char *)memcpy(result, s, len);
 }
 
+#ifdef __cplusplus
+#define STRDUP(x) strdup(x)
+#else
+#define STRDUP(x)
+#endif
 static void nsvg__content(void* ud, const char* s)
 {
 	NSVGparser* p = (NSVGparser*)ud;
@@ -2862,10 +2863,10 @@ static void nsvg__content(void* ud, const char* s)
 		}
 	} else if (p->styleFlag) {
 		// decrease string to cdata content (if present)
-		char* rv = strstr(s, "<![CDATA[");
+		char* rv = STRDUP(strstr(s, "<![CDATA["));
 		if (rv) {
 			s = rv + 9;
-			rv = strstr(s, "]]>");
+			rv = STRDUP(strstr(s, "]]>"));
 			if (!rv)
 				return;
 			else *rv = '\0';
@@ -2924,6 +2925,7 @@ static void nsvg__content(void* ud, const char* s)
 		//}
 	}
 }
+#undef STRDUP
 
 static void nsvg__imageBounds(NSVGparser* p, float* bounds)
 {
```

**Comment by boris-ulyanov** [comment]
Yes, you are correct, I don't checked with С++.
But your solution has memory leak.
May be better remove `const` attribute from `s`?

```diff
@@ -241,7 +241,7 @@ static NSVG_INLINE float nsvg__maxf(float a, float b) { return a > b ? a : b; }
 #define NSVG_XML_MAX_ATTRIBS 256
 
 static void nsvg__parseContent(char* s,
-                                                          void (*contentCb)(void* ud, const char* s),
+                                                          void (*contentCb)(void* ud, char* s),
                                                           void* ud)
 {
        // Trim start white spaces
@@ -331,7 +331,7 @@ static void nsvg__parseElement(char* s,
 int nsvg__parseXML(char* input,
                                   void (*startelCb)(void* ud, const char* el, const char** attr),
                                   void (*endelCb)(void* ud, const char* el),
-                                  void (*contentCb)(void* ud, const char* s),
+                                  void (*contentCb)(void* ud, char* s),
                                   void* ud)
 {
        char* s = input;
@@ -2835,7 +2835,7 @@ static char *nsvg__strndup(const char *s, size_t n)
        return (char *)memcpy(result, s, len);
 }
 
-static void nsvg__content(void* ud, const char* s)
+static void nsvg__content(void* ud, char* s)
 {
        NSVGparser* p = (NSVGparser*)ud;
        if (p->titleFlag) {
```

**Comment by darealshinji** [comment]
I removed the `const` attributes.

**Pull request merged**
